# Generated by Django 4.0.4 on 2022-04-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('no_of_rooms', models.IntegerField()),
                ('no_of_members', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(default='')),
                ('city', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('Room_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total_rooms', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='images')),
                ('price', models.IntegerField(default='0')),
            ],
        ),
    ]
