# Generated by Django 4.0.4 on 2022-05-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelAutomationSystem', '0002_customer1_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseKeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roomno', models.CharField(max_length=10)),
                ('HouseKeepingRequest', models.TextField()),
            ],
        ),
    ]
